"""
Trading Lab — Database Initialization
======================================

Creates the SQLite database schema and seeds it with:
- VCF strategy definition
- NIFTY instrument
- 5 test categories
- All 28 test definitions

Run once:  python scripts/init_db.py
Re-run:    safe — uses IF NOT EXISTS and INSERT OR IGNORE

To reset:  python scripts/init_db.py --reset
"""

import argparse
import sys
from pathlib import Path

# Add project root to path.
_ROOT = str(Path(__file__).resolve().parent.parent)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from infrastructure.db import get_connection, get_db_path


# ── Schema ──────────────────────────────────────────────────────────

_SCHEMA = """
-- Strategies (VCF, future strategies)
CREATE TABLE IF NOT EXISTS strategies (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT NOT NULL,
    slug          TEXT NOT NULL UNIQUE,
    description   TEXT,
    created_at    TEXT DEFAULT (datetime('now'))
);

-- Instruments a strategy can be tested against
CREATE TABLE IF NOT EXISTS instruments (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT NOT NULL,
    symbol        TEXT NOT NULL UNIQUE,
    asset_type    TEXT NOT NULL
);

-- Test categories within a strategy
CREATE TABLE IF NOT EXISTS test_categories (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_id   INTEGER NOT NULL REFERENCES strategies(id),
    name          TEXT NOT NULL,
    slug          TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    UNIQUE(strategy_id, slug)
);

-- Individual test definitions
CREATE TABLE IF NOT EXISTS tests (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    category_id   INTEGER NOT NULL REFERENCES test_categories(id),
    test_number   INTEGER NOT NULL,
    name          TEXT NOT NULL,
    slug          TEXT NOT NULL,
    description   TEXT,
    UNIQUE(category_id, test_number)
);

-- Each run of a test against an instrument
CREATE TABLE IF NOT EXISTS test_runs (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    test_id             INTEGER NOT NULL REFERENCES tests(id),
    instrument_id       INTEGER NOT NULL REFERENCES instruments(id),
    run_at              TEXT NOT NULL,
    duration_seconds    REAL,
    status              TEXT NOT NULL DEFAULT 'running',
    data_window_start   TEXT,
    data_window_end     TEXT,
    config_snapshot     TEXT,
    row_count           INTEGER,
    terminal_output     TEXT,
    notes               TEXT
);

-- Key findings from each run
CREATE TABLE IF NOT EXISTS insights (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    test_run_id     INTEGER NOT NULL REFERENCES test_runs(id),
    insight_key     TEXT NOT NULL,
    insight_value   TEXT,
    insight_text    TEXT NOT NULL,
    severity        TEXT DEFAULT 'info',
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Charts generated by each run
CREATE TABLE IF NOT EXISTS charts (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    test_run_id     INTEGER NOT NULL REFERENCES test_runs(id),
    filename        TEXT NOT NULL,
    title           TEXT,
    chart_type      TEXT,
    description     TEXT,
    plotly_json     TEXT
);

-- Data tables generated by each run
CREATE TABLE IF NOT EXISTS data_tables (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    test_run_id     INTEGER NOT NULL REFERENCES test_runs(id),
    filename        TEXT NOT NULL,
    title           TEXT,
    description     TEXT,
    row_count       INTEGER,
    column_count    INTEGER,
    data_json       TEXT
);
"""


# ── Seed Data ───────────────────────────────────────────────────────

_SEED_STRATEGIES = [
    (
        "Velocity Capture Framework",
        "vcf",
        "Options-based directional strategy built around Nifty index "
        "moves conditioned on India VIX regimes. Targets a 100-150 "
        "point capture zone within the daily expected move.",
    ),
]

_SEED_INSTRUMENTS = [
    ("Nifty 50", "NIFTY", "index"),
]

_SEED_CATEGORIES = [
    # (strategy_slug, name, slug, display_order)
    ("vcf", "Foundation", "foundation", 1),
    ("vcf", "Move Characteristics", "move_characteristics", 2),
    ("vcf", "VIX Regime", "vix_regime", 3),
    ("vcf", "Options Simulation", "options_simulation", 4),
    ("vcf", "Framework Performance", "framework_performance", 5),
]

_SEED_TESTS = [
    # (category_slug, test_number, name, slug, description)
    # Foundation (1-6)
    ("foundation", 1, "Data Integrity",
     "t01_data_integrity",
     "Validate raw Nifty and VIX data for gaps, spikes, and corrupt candles"),
    ("foundation", 2, "Session Boundaries",
     "t02_session_boundaries",
     "Confirm market hours, opening range, and session filtering work correctly"),
    ("foundation", 3, "VIX Regime Classification",
     "t03_vix_regime_classification",
     "Test all six VIX band boundaries and edge cases"),
    ("foundation", 4, "DVR Calculation",
     "t04_dvr_calculation",
     "Validate Daily Volatility Reference against manual calculations"),
    ("foundation", 5, "Capture Zone Definition",
     "t05_capture_zone_definition",
     "Test capture zone min/max against DVR across regime samples"),
    ("foundation", 6, "Basic Statistics",
     "t06_basic_statistics",
     "Verify summary statistics computation for price and VIX series"),

    # Move Characteristics (7-12)
    ("move_characteristics", 7, "Intraday Range Distribution",
     "t07_intraday_range",
     "Profile high-low ranges by VIX regime and day of week"),
    ("move_characteristics", 8, "Directional Move Frequency",
     "t08_directional_move_freq",
     "Measure % of days with moves exceeding capture zone thresholds"),
    ("move_characteristics", 9, "Move Timing",
     "t09_move_timing",
     "Analyse when capture-zone moves typically begin and complete"),
    ("move_characteristics", 10, "Opening Range Breakout",
     "t10_opening_range_breakout",
     "Test 15-min opening range as directional signal"),
    ("move_characteristics", 11, "Overnight Gap Behaviour",
     "t11_overnight_gap_behaviour",
     "Profile gap-up/gap-down frequency and fill rates"),
    ("move_characteristics", 12, "Multi-Timeframe Alignment",
     "t12_multi_timeframe_alignment",
     "Cross-validate signals across 1min, 15min, and daily views"),

    # VIX Regime (13-17)
    ("vix_regime", 13, "Regime Transition Frequency",
     "t13_regime_transition_freq",
     "How often VIX moves between adjacent bands"),
    ("vix_regime", 14, "Regime Duration",
     "t14_regime_duration",
     "Average and median days spent in each band"),
    ("vix_regime", 15, "Regime-Return Mapping",
     "t15_regime_return_mapping",
     "Expected Nifty move distribution per VIX band"),
    ("vix_regime", 16, "VIX Direction Impact",
     "t16_vix_direction_impact",
     "Test downgrade threshold (5%) on trade eligibility"),
    ("vix_regime", 17, "Regime Stability Intraday",
     "t17_regime_stability_intraday",
     "Does the VIX band change within a single trading session?"),

    # Options Simulation (18-23)
    ("options_simulation", 18, "ATM Premium Estimation",
     "t18_atm_premium_estimation",
     "Black-Scholes premium vs actual ATM premium accuracy"),
    ("options_simulation", 19, "Premium Decay Profile",
     "t19_premium_decay_profile",
     "Theta decay across the session for same-week expiry ATM"),
    ("options_simulation", 20, "Stop-Loss Mechanics",
     "t20_stop_loss_mechanics",
     "Validate 17.5% preferred and 35% max premium stop triggers"),
    ("options_simulation", 21, "Time Stop Enforcement",
     "t21_time_stop_enforcement",
     "Test 45-min and 50-min time stop behaviour"),
    ("options_simulation", 22, "Target Return Validation",
     "t22_target_return_validation",
     "20-50% return targets against actual premium moves"),
    ("options_simulation", 23, "Transaction Cost Impact",
     "t23_transaction_cost_impact",
     "Compare P&L under optimistic (5), realistic (8), conservative (12) costs"),

    # Framework Performance (24-28)
    ("framework_performance", 24, "Walk-Forward Backtest",
     "t24_walk_forward_backtest",
     "70/30 train/test split with rolling window validation"),
    ("framework_performance", 25, "Monte Carlo Simulation",
     "t25_monte_carlo_simulation",
     "10,000 simulations on minimum 150-trade sample"),
    ("framework_performance", 26, "Risk of Ruin",
     "t26_risk_of_ruin",
     "Calculate probability of drawdown beyond risk parameters"),
    ("framework_performance", 27, "Regime-Filtered Performance",
     "t27_regime_filtered_performance",
     "Equity curves separated by VIX band"),
    ("framework_performance", 28, "Full Framework Report",
     "t28_full_framework_report",
     "Aggregate all results into publishable report with charts"),
]


def create_schema(conn):
    """Create all tables."""
    conn.executescript(_SCHEMA)
    print("  [OK]  Schema created (7 tables)")


def seed_data(conn):
    """Insert seed data (strategies, instruments, categories, tests)."""

    # Strategies
    for name, slug, desc in _SEED_STRATEGIES:
        conn.execute(
            "INSERT OR IGNORE INTO strategies (name, slug, description) "
            "VALUES (?, ?, ?)",
            (name, slug, desc),
        )
    print("  [OK]  Strategies seeded")

    # Instruments
    for name, symbol, asset_type in _SEED_INSTRUMENTS:
        conn.execute(
            "INSERT OR IGNORE INTO instruments (name, symbol, asset_type) "
            "VALUES (?, ?, ?)",
            (name, symbol, asset_type),
        )
    print("  [OK]  Instruments seeded")

    # Categories — look up strategy_id by slug
    for strat_slug, name, slug, order in _SEED_CATEGORIES:
        row = conn.execute(
            "SELECT id FROM strategies WHERE slug = ?", (strat_slug,)
        ).fetchone()
        if row:
            conn.execute(
                "INSERT OR IGNORE INTO test_categories "
                "(strategy_id, name, slug, display_order) VALUES (?, ?, ?, ?)",
                (row["id"], name, slug, order),
            )
    print(f"  [OK]  {len(_SEED_CATEGORIES)} categories seeded")

    # Tests — look up category_id by slug
    inserted = 0
    for cat_slug, num, name, slug, desc in _SEED_TESTS:
        row = conn.execute(
            "SELECT id FROM test_categories WHERE slug = ?", (cat_slug,)
        ).fetchone()
        if row:
            conn.execute(
                "INSERT OR IGNORE INTO tests "
                "(category_id, test_number, name, slug, description) "
                "VALUES (?, ?, ?, ?, ?)",
                (row["id"], num, name, slug, desc),
            )
            inserted += 1
    print(f"  [OK]  {inserted} tests seeded")

    conn.commit()


def reset_db():
    """Delete the database file entirely."""
    db_path = get_db_path()
    if db_path.exists():
        db_path.unlink()
        # Also remove WAL and SHM files if present.
        for suffix in ("-wal", "-shm"):
            p = db_path.parent / (db_path.name + suffix)
            if p.exists():
                p.unlink()
        print(f"  [OK]  Deleted {db_path}")
    else:
        print(f"  [--]  No database found at {db_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Initialize the Trading Lab SQLite database"
    )
    parser.add_argument(
        "--reset", action="store_true",
        help="Delete existing database before recreating",
    )
    args = parser.parse_args()

    print("=" * 55)
    print("  Trading Lab — Database Initialization")
    print("=" * 55)

    if args.reset:
        print("\n  Resetting database...")
        reset_db()

    print(f"\n  Database: {get_db_path()}")

    conn = get_connection()
    try:
        create_schema(conn)
        seed_data(conn)

        # Verify
        counts = {}
        for table in ["strategies", "instruments", "test_categories", "tests"]:
            row = conn.execute(f"SELECT COUNT(*) as c FROM {table}").fetchone()
            counts[table] = row["c"]

        print("\n  Verification:")
        for table, count in counts.items():
            print(f"    {table:20s}  {count} rows")

        print("\n" + "=" * 55)
        print("  Done. Database ready.")
        print("=" * 55)
    finally:
        conn.close()


if __name__ == "__main__":
    main()
